[apt]
packages = ["libegl1", "libegl-dev", "libgl1-mesa-glx", "libosmesa6-dev", "libgl1", "libopengl0", "libglu1-mesa"]

[node_packs]
ComfyUI-GeometryPack = "PozzettiAndrea/ComfyUI-GeometryPack"
ComfyUI-Multiband = "PozzettiAndrea/ComfyUI-Multiband"
